import Head from "next/head";
import styles from "../styles/Home.module.css";
import { projectSeed } from "../seed";
import logo from "../img/logo.png";
import { useEffect, useState } from "react";
import SimpleSlider from "../component/slider";
import FullView from "../component/fullView";

export default function Home() {
  const [projectId, setProjectId] = useState("a");
  const [sectionId, setSectionId] = useState("");
  const [isFullViewActive, setIsFullViewActive] = useState(false);

  function ButtonHandler(e: any) {
    const SectionId = e.getAttribute("data-id");
    setSectionId(SectionId);
  }

  useEffect(() => {
    const active = document.getElementsByClassName(`${styles.active}`)[0];
    active?.scrollIntoView({ behavior: "smooth" });
  }, [projectId]);
  return (
    <div>
      <Head>
        <title>
          Türkiye'nin En Büyük Online Alışveriş Sitesi Hepsiburada.com
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={logo} />
      </Head>

      <div className={styles.container}>
        <div className={styles.title}>
          {projectSeed.map((project) => (
            <span
              className={
                projectId[0].toUpperCase() === project.id ? styles.active : ""
              }
              onClick={(e) => ButtonHandler(e.currentTarget)}
              key={project.id}
              data-id={project.id}
            >
              {project.title}
            </span>
          ))}
        </div>
      </div>
      <SimpleSlider
        setProjectId={setProjectId}
        projectId={projectId}
        sectionId={sectionId}
        setSectionId={setSectionId}
        isFullViewActive={isFullViewActive}
        setIsFullViewActive={setIsFullViewActive}
      />
      <FullView
        isFullViewActive={isFullViewActive}
        setIsFullViewActive={setIsFullViewActive}
        projectId={projectId}
      />
    </div>
  );
}
